services:
  certifier:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: certifier
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
